"""
失败原因枚举码：用于链路可观测与自动修复决策。
"""
from __future__ import annotations

from enum import Enum


class FailureCode(str, Enum):
    # 意图/规划
    INTENT_UNAVAILABLE = "INTENT_UNAVAILABLE"
    PLAN_EMPTY = "PLAN_EMPTY"
    PLAN_INVALID = "PLAN_INVALID"

    # 检索与记忆
    MEMORY_QUERY_FAILED = "MEMORY_QUERY_FAILED"
    WEB_SEARCH_FAILED = "WEB_SEARCH_FAILED"
    KB_RETRIEVE_FAILED = "KB_RETRIEVE_FAILED"

    # 执行
    STEP_TIMEOUT = "STEP_TIMEOUT"
    STEP_EXCEPTION = "STEP_EXCEPTION"
    PLUGIN_NOT_FOUND = "PLUGIN_NOT_FOUND"
    PLUGIN_EMPTY_RESULT = "PLUGIN_EMPTY_RESULT"
    RETRY_EXHAUSTED = "RETRY_EXHAUSTED"
    FALLBACK_APPLIED = "FALLBACK_APPLIED"

    # 结束态
    SKIPPED_WITH_EXPLANATION = "SKIPPED_WITH_EXPLANATION"
