"""
兼容层：Plan 相关已迁移至 plans 包，本文件仅做转发，便于旧引用不报错。
请统一改为：from plans import ...
"""
from __future__ import annotations

from plans import (
    CAPABILITY_TEMPLATE_CASE_LIBRARY,
    CAPABILITY_TEMPLATE_CONTENT_DIRECTION_RANKING,
    CAPABILITY_TEMPLATE_CONTENT_POSITIONING_MATRIX,
    CAPABILITY_TEMPLATE_WEEKLY_DECISION_SNAPSHOT,
    IP_INTAKE_OPTIONAL_KEYS,
    IP_INTAKE_REQUIRED_KEYS,
    PLAN_TEMPLATE_DYNAMIC,
    TEMPLATE_ACCOUNT_BUILDING,
    TEMPLATE_CONTENT_MATRIX,
    TEMPLATE_IP_DIAGNOSIS,
    get_fixed_plan,
    list_template_ids,
)

__all__ = [
    "IP_INTAKE_REQUIRED_KEYS",
    "IP_INTAKE_OPTIONAL_KEYS",
    "TEMPLATE_IP_DIAGNOSIS",
    "TEMPLATE_ACCOUNT_BUILDING",
    "TEMPLATE_CONTENT_MATRIX",
    "CAPABILITY_TEMPLATE_CONTENT_DIRECTION_RANKING",
    "CAPABILITY_TEMPLATE_CASE_LIBRARY",
    "CAPABILITY_TEMPLATE_CONTENT_POSITIONING_MATRIX",
    "CAPABILITY_TEMPLATE_WEEKLY_DECISION_SNAPSHOT",
    "PLAN_TEMPLATE_DYNAMIC",
    "get_fixed_plan",
    "list_template_ids",
]
